### ISSUE TITLE
bootstrap name drop down

### ISSUE THREAD

**Issue by LukeCaruzo** [Zeta-Project/zeta#338]
The drop down menu doesn't work when clicking on the name.
<img width="192" alt="Bildschirmfoto 2020-08-13 um 15 13 18" src="https://user-images.githubusercontent.com/23531489/90138616-8d518c80-dd77-11ea-9de9-dc23b86842b5.png">

**Comment by stefan0612** [comment]
Bootstrap-dropdown-menus working fine in new frontend, which is going to be build completely with vue.js
Thus this issue is a won't fix and is going to be resolved with the next stable release of a properly working frontend

**Comment by LukeCaruzo** [comment]
As far as I got, the problem was and is that bootstrap is not loaded correctly. 
Sadly it wasn't possible to fix the issue yet.

> frontend, which is going to be build completely with vue.js
> Thus this issue is a won't fix and is going to be resolved with the next stable release of a properly working frontend

Therefore we can close this issue?

**Comment by stefan0612** [comment]
The Problem resulted in bundling bootstrap styles with webpack , but since the new frontend doesnt make use of webpack bundling, this issue is going to be resolved when the new frontend is released (was already tested and works fine in the new frontend) 
Im going to link this issue to the new frontend when its merged in dev
Until then this issue can be leaved open, but dont fix it yet
