### ISSUE TITLE
Concept Editor: usage of backend REST API 

### ISSUE THREAD

**Issue by pat-St** [Zeta-Project/zeta#400]
| Description | URI |
| :---: | :--- |
| get definition Json | /rest/v1/meta-models/:metaModelId  |
| get shape Json | /rest/v2/meta-models/:metaModelId/shape  |
| get style json | /rest/v2/meta-models/:metaModelId/style |
| get diagram json | /rest/v2/meta-models/:metaModelId/diagram  |

**Comment by phbenisc** [comment]
So i looked at the code and i think it is major rework.
So in order to do that I devised the a plan

current plan:

- [ ] 1. add vuex module for graphical editor state

- the route file should be aware of the vuex module to get things

- [ ] 2. move state of editor into vuex module ( getters ) 
- state found in 
-- `CodeEditor.vue` -> `gdslProject`, `dslType`
-- `RESTApi.js` -> hard coded `definition`
-- `GraphEditor` -> see `data` method 
- [ ] 3. add requests to fetch data from backend ( actions )
- see `GraphEditor` method `initGraphComponent` 
- [ ] 4. map retrieved data ( mutations )

**Comment by Sebi1006** [comment]
obsolete
